<?php
/**
 * _edit CMS Configuration - EXAMPLE
 *
 * Copy this file to config.php and customize for your environment.
 * DO NOT edit this file directly - it's a template!
 */

// Security: Encryption key for sensitive data (SMTP passwords, etc.)
// IMPORTANT: Generate a unique random key for production!
// Generate with: openssl rand -hex 32
// Or with: php -r "echo bin2hex(random_bytes(32)) . PHP_EOL;"
define('EDIT_ENCRYPTION_KEY', 'CHANGE_THIS_IN_PRODUCTION_USE_RANDOM_32_BYTE_HEX_STRING');

// CORS: Allowed origins for API requests (development only)
// In production, leave empty array - Vue app served from same origin
define('EDIT_CORS_ORIGINS', [
    'http://localhost:5173',  // Vite dev server
    'http://localhost:3000',
    'http://127.0.0.1:5173',
]);

// Database path (relative to _edit directory)
// Default: /data/database/site.sqlite
define('EDIT_DATABASE_PATH', EDIT_BASE_PATH . '/data/database/site.sqlite');

// Debug mode (set to false in production)
define('EDIT_DEBUG', true);

// Session token expiry (in hours)
define('EDIT_SESSION_EXPIRY_HOURS', 24);

// Pagination defaults
define('EDIT_DEFAULT_PAGE_LIMIT', 10);
define('EDIT_MAX_PAGE_LIMIT', 100);

// File upload limits
// IMPORTANT: Ensure php.ini has upload_max_filesize and post_max_size >= these values
// For shared hosting, see .user.ini in _edit directory
define('EDIT_MAX_FILE_SIZE', 50 * 1024 * 1024); // 50MB
define('EDIT_MAX_IMAGE_WIDTH', 4000);
define('EDIT_MAX_IMAGE_HEIGHT', 4000);

// ZIP validation limits (for config import/export)
define('EDIT_MAX_ZIP_COMPRESSED_SIZE', 10 * 1024 * 1024); // 10MB
define('EDIT_MAX_ZIP_UNCOMPRESSED_SIZE', 50 * 1024 * 1024); // 50MB
define('EDIT_MAX_ZIP_FILES', 1000);
